# Generated by Django 4.1.7 on 2023-03-07 15:59

from django.db import migrations


def resize_all_images(apps, schema_editor):
    Ticket = apps.get_model('reviews', 'Ticket')
    tickets = Ticket.objects.all()
    for ticket in tickets:
        ticket.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(resize_all_images),
    ]
