# Generated by Django 4.1.7 on 2023-03-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230307_1559'),
    ]

    operations = [
    ]
