# Generated by Django 4.1.7 on 2023-03-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230307_1611'),
    ]

    operations = [
    ]
